apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-service
  labels:
    app: verification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: verification
  template:
    metadata:
      labels:
        app: verification
    spec:
      containers:
      - name: verification-container
        image: your-dockerhub-username/verification-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: WORKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: verification-service
spec:
  type: LoadBalancer
  selector:
    app: verification
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
